# Continuous Integration (CI) is the practice, in software
# engineering, of merging all developer working copies with a shared mainline
# several times a day < http://docs.platformio.org/page/ci/index.html >

language: python
python:
    - "2.7"

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change
    
cache:
    directories:
        - "~/.platformio"

env:
    - BOARD=esp01 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266
    - BOARD=nodemcuv2 PLATFORMIO_CI_SRC=examples/SimpleLoggingESP8266

install:
    - pip install -U platformio
    
script:
    - platformio ci -v --lib="." --board=$BOARD $EXTRAS

